// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15wxsFjOCnvHJt6Suij8n10c1pXU8Xfs',
    appId: '1:782370848918:web:677f3f154e1c883df682b7',
    messagingSenderId: '782370848918',
    projectId: 'chat-app-39bf7',
    authDomain: 'chat-app-39bf7.firebaseapp.com',
    storageBucket: 'chat-app-39bf7.appspot.com',
    measurementId: 'G-8CTFR4DK3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAq_7G8MHF4jNIjeo8CRvGz8Wlfi-7lBY',
    appId: '1:782370848918:android:155df2545c1d7c37f682b7',
    messagingSenderId: '782370848918',
    projectId: 'chat-app-39bf7',
    storageBucket: 'chat-app-39bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoRozh9_rZ1cqnAiVs5Icg4nYBgaHqQUA',
    appId: '1:782370848918:ios:6a8f87de6213266bf682b7',
    messagingSenderId: '782370848918',
    projectId: 'chat-app-39bf7',
    storageBucket: 'chat-app-39bf7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoRozh9_rZ1cqnAiVs5Icg4nYBgaHqQUA',
    appId: '1:782370848918:ios:7d7e95afb0084105f682b7',
    messagingSenderId: '782370848918',
    projectId: 'chat-app-39bf7',
    storageBucket: 'chat-app-39bf7.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
